#!/usr/bin/env php

<?php

$autoloadPath1 = __DIR__ . '/../../../autoload.php';
$autoloadPath2 = __DIR__ . '/../../vendor/autoload.php';
if (file_exists($autoloadPath1)) {
    require_once $autoloadPath1;
} else {
    require_once $autoloadPath2;
}

use function cli\line;
use function cli\prompt;
use function Brain\Games\Engine\greeting;
use function Brain\Games\Engine\getPlayersAnswer;
use function Brain\Games\Engine\concratulations;
use function Brain\Games\Engine\isCorrect;
use function Brain\Games\Engine\resultArray;
use function Brain\Games\Engine\gcd;

$playerName = greeting();

line ('Find the greatest common divisor of given numbers.');

for ($numberOfQuestions = 0; $numberOfQuestions < 3; $numberOfQuestions++) {

    $firstNumber = rand(1, 100);
    $secondNumber = rand(1, 100);
    $correctAnswer = gcd($firstNumber, $secondNumber);
    $expression = "$firstNumber $secondNumber";
    $playerAnswer = getPlayersAnswer($expression);

    if (isCorrect($playerAnswer, $correctAnswer)) {
        line('Correct!');
    } else {
        line("'{$playerAnswer}' is wrong answer ;(. Correct answer was '{$correctAnswer}'.");
        line("Let's try again, $playerName!");
        break;
    }
}

concratulations($numberOfQuestions, $playerName);